version: '3.4'

services:
  gptbatchwrapper:
    image: gptbatchwrapper
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/app
